// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef LispCAD_h
#define LispCAD_h
#include <FL/Fl.H>
/**
   Include the Embeddable Common Lisp lib (compiled for C++)
*/
#include <ecl/ecl.h>
#include "CADCanvas.h"
#include "CommandLine.h"
void add_line(cl_object x, cl_object y, cl_object x2, cl_object y2);
void add_circle(cl_object x, cl_object y, cl_object radius);
void test_CB(Fl_Widget* w, void* p);
void commandline_CB_wrapper(Fl_Widget* w, void* p);
cl_object get_int();
void canvas_click(Fl_Widget* w, void* p);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_window;
extern CADCanvas *canvas;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *echo_area;
extern CommandLine *mini_buffer;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *menu_bar;
#include <FL/Fl_Slider.H>
extern Fl_Slider *pan_across;
extern Fl_Slider *pan_vert;
extern Fl_Menu_Item menu_menu_bar[];
#define file_menu (menu_menu_bar+0)
#define file_new_item (menu_menu_bar+1)
#define file_save_item (menu_menu_bar+2)
#define file_save_as_item (menu_menu_bar+3)
#define file_quit_item (menu_menu_bar+4)
#define edit_menu (menu_menu_bar+6)
#define lisp_menu (menu_menu_bar+8)
#define lisp_refresh_scripts_item (menu_menu_bar+9)
#define lisp_repl_item (menu_menu_bar+10)
#endif
